In [9]:
import tensorflow as tf
from numpy.random import RandomState

In [14]:
batch_size = 8

x = tf.placeholder(tf.float32,shape=(None,2),name='x_input')
y_ = tf.placeholder(tf.float32,shape=(None,1),name='y_input')

w1 = tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y = tf.matmul(x,w1)

loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y,y_),
                               (y-y_)*loss_more,(y_-y)*loss_less))
# 原书用的不是where()是select()，但是select报错没这个模块
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

In [15]:
rdm = RandomState(1)
datase_size = 128
X = rdm.rand(datase_size,2)

Y = [[x1 + x2 + rdm.rand()/10.0-0.05] for (x1,x2) in X]

In [16]:
with tf.Session() as sess:
    init_op = tf.initialize_all_variables()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size)%datase_size
        end = min(start+batch_size,datase_size)
        sess.run(train_step,
                feed_dict={x:X[start:end],y_:Y[start:end]})
        print(sess.run(w1))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[-0.81031823]
 [ 1.4855988 ]]
[[-0.8093366]
 [ 1.4865911]]
[[-0.8083831]
 [ 1.4875891]]
[[-0.8074217]
 [ 1.488542 ]]
[[-0.80644417]
 [ 1.4894979 ]]
[[-0.8054569]
 [ 1.490472 ]]
[[-0.8044624]
 [ 1.4914528]]
[[-0.8034634]
 [ 1.4924384]]
[[-0.80245554]
 [ 1.4934249 ]]
[[-0.80146426]
 [ 1.4944159 ]]
[[-0.80048096]
 [ 1.4954216 ]]
[[-0.79950386]
 [ 1.4964081 ]]
[[-0.79850495]
 [ 1.4974177 ]]
[[-0.7975289]
 [ 1.4984025]]
[[-0.7965442]
 [ 1.4994123]]
[[-0.79556257]
 [ 1.5004357 ]]
[[-0.7946243]
 [ 1.5014318]]
[[-0.7936975]
 [ 1.5024269]]
[[-0.79274493]
 [ 1.5034243 ]]
[[-0.79180086]
 [ 1.504382  ]]
[[-0.7908325]
 [ 1.5053244]]
[[-0.78985554]
 [ 1.5062915 ]]
[[-0.78887033]
 [ 1.5072582 ]]
[[-0.7878793]
 [ 1.5082244]]
[[-0.78687394]
 [ 1.5091867 ]]
[[-0.78588563]
 [ 1.5101508 ]]
[[-0.78490686]
 [ 1.5111339 ]]
[[-0.7839362]
 [ 1.5120951]]
[[-0.78293514]
 [ 1.5130919 ]]
[[-0.7819587]
 [ 1.5140618]]
[[-0.78097296]
 [ 1.5150

[[-0.50674385]
 [ 1.7692552 ]]
[[-0.5058632]
 [ 1.7700598]]
[[-0.50493956]
 [ 1.7708642 ]]
[[-0.5040191]
 [ 1.7716614]]
[[-0.5030787]
 [ 1.772483 ]]
[[-0.5021223]
 [ 1.7733262]]
[[-0.50114036]
 [ 1.7741735 ]]
[[-0.50019723]
 [ 1.774963  ]]
[[-0.4992768]
 [ 1.7757541]]
[[-0.4983672]
 [ 1.7765132]]
[[-0.49740243]
 [ 1.7773601 ]]
[[-0.49647427]
 [ 1.77816   ]]
[[-0.4955357]
 [ 1.7790109]]
[[-0.49461582]
 [ 1.7798529 ]]
[[-0.49374208]
 [ 1.7806863 ]]
[[-0.4928893]
 [ 1.7815207]]
[[-0.4920009]
 [ 1.7823584]]
[[-0.49111864]
 [ 1.7831681 ]]
[[-0.4901933]
 [ 1.7839774]]
[[-0.48927113]
 [ 1.7847793 ]]
[[-0.48832902]
 [ 1.7856058 ]]
[[-0.48737085]
 [ 1.7864541 ]]
[[-0.4863871]
 [ 1.7873064]]
[[-0.48544228]
 [ 1.7881006 ]]
[[-0.4845202]
 [ 1.7888963]]
[[-0.483609 ]
 [ 1.7896599]]
[[-0.48264244]
 [ 1.7905117 ]]
[[-0.48171264]
 [ 1.7913163 ]]
[[-0.48078582]
 [ 1.7921426 ]]
[[-0.47987637]
 [ 1.792963  ]]
[[-0.47901195]
 [ 1.7937775 ]]
[[-0.4781675]
 [ 1.7945955]]
[[-0.4772863]
 [ 1.795419 ]]
[[-0.47

[[-0.22870566]
 [ 1.999257  ]]
[[-0.22790883]
 [ 1.9998341 ]]
[[-0.22711203]
 [ 2.000413  ]]
[[-0.22630952]
 [ 2.0009892 ]]
[[-0.22551349]
 [ 2.0015523 ]]
[[-0.22468905]
 [ 2.0021145 ]]
[[-0.22388437]
 [ 2.0026507 ]]
[[-0.22312364]
 [ 2.0031583 ]]
[[-0.22237039]
 [ 2.003629  ]]
[[-0.22155619]
 [ 2.0042038 ]]
[[-0.22076608]
 [ 2.0047498 ]]
[[-0.2199943]
 [ 2.0052977]]
[[-0.21926315]
 [ 2.005803  ]]
[[-0.218605 ]
 [ 2.0062456]]
[[-0.21796118]
 [ 2.006709  ]]
[[-0.21725242]
 [ 2.0072272 ]]
[[-0.21652661]
 [ 2.0077577 ]]
[[-0.21573284]
 [ 2.008329  ]]
[[-0.21493842]
 [ 2.008903  ]]
[[-0.21413766]
 [ 2.0094755 ]]
[[-0.21334288]
 [ 2.0100355 ]]
[[-0.21251905]
 [ 2.0105956 ]]
[[-0.21171464]
 [ 2.01113   ]]
[[-0.210954 ]
 [ 2.0116363]]
[[-0.2102005]
 [ 2.0121057]]
[[-0.20938545]
 [ 2.012681  ]]
[[-0.20859432]
 [ 2.0132277 ]]
[[-0.20782137]
 [ 2.0137768 ]]
[[-0.20708899]
 [ 2.0142834 ]]
[[-0.20642975]
 [ 2.0147269 ]]
[[-0.20578472]
 [ 2.0151918 ]]
[[-0.2050743]
 [ 2.015712 ]]
[[-0.20434658]
 [ 

 [ 2.1173787 ]]
[[-0.02920121]
 [ 2.117757  ]]
[[-0.02850355]
 [ 2.1181512 ]]
[[-0.02775614]
 [ 2.1185725 ]]
[[-0.02701432]
 [ 2.118988  ]]
[[-0.0263065]
 [ 2.119392 ]]
[[-0.02559376]
 [ 2.1197717 ]]
[[-0.02487678]
 [ 2.1201816 ]]
[[-0.02420288]
 [ 2.1205359 ]]
[[-0.02357942]
 [ 2.1208434 ]]
[[-0.0229781]
 [ 2.1211348]]
[[-0.0224371]
 [ 2.1213815]]
[[-0.02195655]
 [ 2.1215835 ]]
[[-0.02140631]
 [ 2.1218429 ]]
[[-0.02084379]
 [ 2.1221027 ]]
[[-0.02020949]
 [ 2.1224115 ]]
[[-0.01955006]
 [ 2.1227617 ]]
[[-0.01886167]
 [ 2.123144  ]]
[[-0.01816018]
 [ 2.1235418 ]]
[[-0.01740867]
 [ 2.1239674 ]]
[[-0.01669916]
 [ 2.124342  ]]
[[-0.01602024]
 [ 2.1247091 ]]
[[-0.01533307]
 [ 2.125056  ]]
[[-0.01463868]
 [ 2.125437  ]]
[[-0.01398499]
 [ 2.1257653 ]]
[[-0.01337963]
 [ 2.1260493 ]]
[[-0.01279439]
 [ 2.1263194 ]]
[[-0.01226788]
 [ 2.1265469 ]]
[[-0.01180042]
 [ 2.1267312 ]]
[[-0.0112613]
 [ 2.1269755]]
[[-0.01070841]
 [ 2.127222  ]]
[[-0.01008204]
 [ 2.1275196 ]]
[[-0.00942926]
 [ 2.1278603 ]]


 [2.1993759]]
[[0.17921314]
 [2.1995027 ]]
[[0.17971128]
 [2.1996243 ]]
[[0.18026823]
 [2.1998172 ]]
[[0.1808231]
 [2.2000117]]
[[0.18142317]
 [2.2002208 ]]
[[0.18200098]
 [2.2003982 ]]
[[0.18254088]
 [2.2005572 ]]
[[0.18311387]
 [2.2007208 ]]
[[0.18365085]
 [2.200874  ]]
[[0.18416685]
 [2.2009935 ]]
[[0.18465054]
 [2.2010865 ]]
[[0.18509784]
 [2.2011473 ]]
[[0.18549359]
 [2.2011764 ]]
[[0.18584223]
 [2.201177  ]]
[[0.18624893]
 [2.201225  ]]
[[0.18669237]
 [2.201301  ]]
[[0.18721041]
 [2.2014291 ]]
[[0.18771166]
 [2.201552  ]]
[[0.18823284]
 [2.201705  ]]
[[0.18875587]
 [2.2018638 ]]
[[0.18932797]
 [2.2020411 ]]
[[0.18988085]
 [2.20219   ]]
[[0.19039842]
 [2.2023232 ]]
[[0.19095191]
 [2.2024636 ]]
[[0.19147147]
 [2.2025962 ]]
[[0.191972 ]
 [2.2026968]]
[[0.1924419]
 [2.2027726]]
[[0.19287685]
 [2.2028177 ]]
[[0.19326141]
 [2.2028325 ]]
[[0.19359994]
 [2.2028198 ]]
[[0.19399817]
 [2.2028565 ]]
[[0.19443451]
 [2.2029228 ]]
[[0.19494697]
 [2.2030425 ]]
[[0.19544342]
 [2.203158  ]]
[[0.19

 [2.2123919]]
[[0.31468138]
 [2.2124307 ]]
[[0.31512913]
 [2.2124557 ]]
[[0.31555846]
 [2.2124722 ]]
[[0.31596354]
 [2.212469  ]]
[[0.31644267]
 [2.212507  ]]
[[0.3169167]
 [2.2125282]]
[[0.31733727]
 [2.212516  ]]
[[0.31781483]
 [2.2125294 ]]
[[0.31826872]
 [2.2125487 ]]
[[0.31871432]
 [2.2125437 ]]
[[0.31913722]
 [2.2125218 ]]
[[0.31953135]
 [2.2124743 ]]
[[0.31987822]
 [2.212401  ]]
[[0.32018176]
 [2.2123039 ]]
[[0.32056057]
 [2.2122738 ]]
[[0.32095528]
 [2.2122529 ]]
[[0.32139933]
 [2.2122583 ]]
[[0.32181856]
 [2.212253  ]]
[[0.32222238]
 [2.2122424 ]]
[[0.3226046]
 [2.2122145]]
[[0.32306394]
 [2.2122307 ]]
[[0.32352045]
 [2.212232  ]]
[[0.3239252]
 [2.2122018]]
[[0.32438916]
 [2.212199  ]]
[[0.3247838]
 [2.212159 ]]
[[0.32517633]
 [2.2121003 ]]
[[0.32555157]
 [2.2120297 ]]
[[0.32590288]
 [2.2119384 ]]
[[0.3262111]
 [2.2118251]]
[[0.32647976]
 [2.211692  ]]
[[0.32682794]
 [2.21163   ]]
[[0.3271954]
 [2.2115803]]
[[0.32761556]
 [2.21156   ]]
[[0.32801336]
 [2.2115316 ]]
[[0.32839808

 [2.1765423 ]]
[[0.44373888]
 [2.1764019 ]]
[[0.44408524]
 [2.1762362 ]]
[[0.44442213]
 [2.1760657 ]]
[[0.44474086]
 [2.1758788 ]]
[[0.44501856]
 [2.175673  ]]
[[0.44525355]
 [2.1754465 ]]
[[0.44553256]
 [2.1752603 ]]
[[0.44584572]
 [2.1750998 ]]
[[0.44623023]
 [2.174985  ]]
[[0.44655582]
 [2.1748352 ]]
[[0.44687942]
 [2.174693  ]]
[[0.44719228]
 [2.174543  ]]
[[0.44756112]
 [2.1744199 ]]
[[0.44794282]
 [2.174293  ]]
[[0.44827917]
 [2.1741407 ]]
[[0.4486971]
 [2.1740332]]
[[0.44904664]
 [2.1738908 ]]
[[0.44939435]
 [2.173723  ]]
[[0.4497326]
 [2.1735504]]
[[0.45005268]
 [2.1733613 ]]
[[0.4503315]
 [2.1731532]]
[[0.45056742]
 [2.1729243 ]]
[[0.4508477]
 [2.172736 ]]
[[0.45116243]
 [2.1725738 ]]
[[0.451549 ]
 [2.1724575]]
[[0.4518763]
 [2.172306 ]]
[[0.45220166]
 [2.1721623 ]]
[[0.45251626]
 [2.1720107 ]]
[[0.4528872]
 [2.1718862]]
[[0.45327115]
 [2.1717582 ]]
[[0.45360947]
 [2.1716042 ]]
[[0.45402992]
 [2.1714954 ]]
[[0.45438156]
 [2.1713517 ]]
[[0.45473137]
 [2.1711822 ]]
[[0.4550717]


 [2.1002805 ]]
[[0.5498138]
 [2.099977 ]]
[[0.55001366]
 [2.0996547 ]]
[[0.55022585]
 [2.0993488 ]]
[[0.55048865]
 [2.099082  ]]
[[0.55081767]
 [2.0988579 ]]
[[0.55109006]
 [2.0986009 ]]
[[0.5513118]
 [2.098319 ]]
[[0.55153626]
 [2.098039  ]]
[[0.55183923]
 [2.0978012 ]]
[[0.55216944]
 [2.097568  ]]
[[0.5524582]
 [2.0973125]]
[[0.5528072]
 [2.0970867]]
[[0.55309045]
 [2.0968292 ]]
[[0.5533836]
 [2.09655  ]]
[[0.55367666]
 [2.096273  ]]
[[0.5539585]
 [2.0959833]]
[[0.55420136]
 [2.0956774 ]]
[[0.55440253]
 [2.0953524 ]]
[[0.55461615]
 [2.0950441 ]]
[[0.5548807]
 [2.0947752]]
[[0.55521184]
 [2.0945492 ]]
[[0.555486]
 [2.09429 ]]
[[0.5557092]
 [2.094006 ]]
[[0.55593514]
 [2.0937235 ]]
[[0.55624014]
 [2.093484  ]]
[[0.5565725]
 [2.0932488]]
[[0.5568632]
 [2.092991 ]]
[[0.55721444]
 [2.0927637 ]]
[[0.5574995]
 [2.092504 ]]
[[0.5577946]
 [2.0922227]]
[[0.55808955]
 [2.0919435 ]]
[[0.5583732]
 [2.0916517]]
[[0.5586177]
 [2.0913434]]
[[0.5588202]
 [2.091016 ]]
[[0.5590352]
 [2.0907054]]
[[0.55

[[0.63125575]
 [1.9746985 ]]
[[0.6314121]
 [1.9742802]]
[[0.63163626]
 [1.9739139 ]]
[[0.6318742]
 [1.9735553]]
[[0.6320607]
 [1.9731674]]
[[0.63220125]
 [1.9727589 ]]
[[0.6323567]
 [1.9723599]]
[[0.6326139]
 [1.9720178]]
[[0.6328684]
 [1.9716593]]
[[0.6330877]
 [1.9712828]]
[[0.6333885]
 [1.9709492]]
[[0.6336233]
 [1.9705848]]
[[0.63387907]
 [1.970201  ]]
[[0.6340815]
 [1.9697862]]
[[0.63428456]
 [1.9693654 ]]
[[0.6344548]
 [1.9689335]]
[[0.63458765]
 [1.9684864 ]]
[[0.634745 ]
 [1.9680654]]
[[0.6349706]
 [1.9676965]]
[[0.6352101]
 [1.9673356]]
[[0.63539773]
 [1.9669452 ]]
[[0.6355392]
 [1.9665339]]
[[0.6356956]
 [1.9661323]]
[[0.63595444]
 [1.9657879 ]]
[[0.63621056]
 [1.9654272 ]]
[[0.6364312]
 [1.9650482]]
[[0.63673395]
 [1.9647123 ]]
[[0.6369702]
 [1.9643455]]
[[0.6372276]
 [1.9639592]]
[[0.63743126]
 [1.9635416 ]]
[[0.6376356]
 [1.963118 ]]
[[0.6378069]
 [1.9626832]]
[[0.6379406]
 [1.9622332]]
[[0.63809896]
 [1.9618093 ]]
[[0.6383259]
 [1.9614381]]
[[0.6385669]
 [1.9610747]]
[[0.

 [1.8121535 ]]
[[0.7167491]
 [1.8116916]]
[[0.7168919]
 [1.8112069]]
[[0.71705383]
 [1.8107344 ]]
[[0.7172638]
 [1.8102916]]
[[0.71747935]
 [1.8098346 ]]
[[0.717662 ]
 [1.8093606]]
[[0.7179457]
 [1.8089399]]
[[0.71815956]
 [1.8084869 ]]
[[0.7184033]
 [1.8080145]]
[[0.71859056]
 [1.8075086 ]]
[[0.7187832]
 [1.8069981]]
[[0.71894205]
 [1.8064772 ]]
[[0.71906155]
 [1.8059406 ]]
[[0.71921265]
 [1.8054359 ]]
[[0.71944547]
 [1.8049935 ]]
[[0.71969706]
 [1.8045615 ]]
[[0.7198913]
 [1.8040967]]
[[0.7200344]
 [1.8036089]]
[[0.72019684]
 [1.8031332 ]]
[[0.72040766]
 [1.8026878 ]]
[[0.7206241]
 [1.8022277]]
[[0.72080743]
 [1.8017508 ]]
[[0.7210926]
 [1.8013275]]
[[0.72130746]
 [1.8008717 ]]
[[0.7215524]
 [1.8003964]]
[[0.72174054]
 [1.7998874 ]]
[[0.72193414]
 [1.799374  ]]
[[0.72209376]
 [1.7988498 ]]
[[0.7222138]
 [1.79831  ]]
[[0.7223657]
 [1.7978023]]
[[0.7225998]
 [1.7973572]]
[[0.7228528]
 [1.7969227]]
[[0.72304815]
 [1.7964551 ]]
[[0.7231921]
 [1.7959645]]
[[0.7233554]
 [1.7954861]]
[[0.72

 [1.6238524]]
[[0.79096985]
 [1.6233104 ]]
[[0.7911401]
 [1.6227784]]
[[0.79132366]
 [1.6222332 ]]
[[0.79147583]
 [1.6216716 ]]
[[0.7917494]
 [1.6211728]]
[[0.79194814]
 [1.6206397 ]]
[[0.7921856]
 [1.6200866]]
[[0.7923626]
 [1.6194974]]
[[0.79254943]
 [1.6189048 ]]
[[0.79270095]
 [1.6183017 ]]
[[0.79281044]
 [1.6176823 ]]
[[0.79295886]
 [1.6171002 ]]
[[0.79320323]
 [1.6165897 ]]
[[0.7934713]
 [1.616092 ]]
[[0.79367566]
 [1.615558  ]]
[[0.7938233]
 [1.6149988]]
[[0.7939946]
 [1.6144542]]
[[0.7941658]
 [1.6139195]]
[[0.7943504]
 [1.6133715]]
[[0.7945034]
 [1.6128072]]
[[0.7947785]
 [1.612306 ]]
[[0.7949784]
 [1.6117703]]
[[0.79521716]
 [1.6112145 ]]
[[0.79539514]
 [1.6106225 ]]
[[0.795583]
 [1.610027]]
[[0.7957354]
 [1.6094209]]
[[0.7958455]
 [1.6087985]]
[[0.79599476]
 [1.6082135 ]]
[[0.7962405]
 [1.6077005]]
[[0.79651004]
 [1.6072003 ]]
[[0.79671556]
 [1.6066636 ]]
[[0.79686403]
 [1.6061016 ]]
[[0.79703635]
 [1.6055543 ]]
[[0.7972085]
 [1.605017 ]]
[[0.79739416]
 [1.6044663 ]]
[[0.797

 [1.4288995 ]]
[[0.8554777]
 [1.4283593]]
[[0.85568786]
 [1.42778   ]]
[[0.85596293]
 [1.4272028 ]]
[[0.85616916]
 [1.4265823 ]]
[[0.85638577]
 [1.4259549 ]]
[[0.856562 ]
 [1.4253131]]
[[0.85669035]
 [1.4246509 ]]
[[0.85686195]
 [1.4240276 ]]
[[0.8570751]
 [1.423452 ]]
[[0.857321 ]
 [1.4228917]]
[[0.85750085]
 [1.4222924 ]]
[[0.85764176]
 [1.4216934 ]]
[[0.8578118]
 [1.4211087]]
[[0.85798395]
 [1.4205332 ]]
[[0.85817325]
 [1.4199414 ]]
[[0.8583288]
 [1.4193302]]
[[0.8586234]
 [1.4187876]]
[[0.85883474]
 [1.4182056 ]]
[[0.8591113]
 [1.4176258]]
[[0.8593186]
 [1.4170024]]
[[0.8595364]
 [1.4163722]]
[[0.8597136]
 [1.4157275]]
[[0.85984266]
 [1.4150622 ]]
[[0.8600152]
 [1.4144361]]
[[0.8602295]
 [1.4138579]]
[[0.86047673]
 [1.4132951 ]]
[[0.8606576]
 [1.412693 ]]
[[0.8607992]
 [1.4120914]]
[[0.86097014]
 [1.411504  ]]
[[0.8611432]
 [1.4109259]]
[[0.8613335]
 [1.4103315]]
[[0.8614899]
 [1.4097174]]
[[0.86178607]
 [1.4091723 ]]
[[0.86199856]
 [1.4085877 ]]
[[0.8622766]
 [1.4080052]]
[[0.8624

[[0.9314263]
 [1.1994158]]
[[0.931638 ]
 [1.1987675]]
[[0.93181205]
 [1.198098  ]]
[[0.9321415]
 [1.1975034]]
[[0.9323778]
 [1.196866 ]]
[[0.93268704]
 [1.1962309 ]]
[[0.93291885]
 [1.1955482 ]]
[[0.93316233]
 [1.194858  ]]
[[0.93336046]
 [1.1941519 ]]
[[0.93350476]
 [1.1934234 ]]
[[0.9336977]
 [1.1927377]]
[[0.9338737]
 [1.1920928]]
[[0.9340929]
 [1.1914659]]
[[0.9342435]
 [1.1907971]]
[[0.93435544]
 [1.1901299 ]]
[[0.9345048]
 [1.189479 ]]
[[0.9346607]
 [1.1888391]]
[[0.93476695]
 [1.1881794 ]]
[[0.9348459]
 [1.1874992]]
[[0.9350907]
 [1.1868951]]
[[0.9352506]
 [1.1862487]]
[[0.93549144]
 [1.1856052 ]]
[[0.9356615]
 [1.1849146]]
[[0.93584955]
 [1.184217  ]]
[[0.93599766]
 [1.183504  ]]
[[0.9360967]
 [1.1827688]]
[[0.93624926]
 [1.1820772 ]]
[[0.9363889]
 [1.1814268]]
[[0.93657565]
 [1.1807947 ]]
[[0.9366968]
 [1.180121 ]]
[[0.9367821]
 [1.179449 ]]
[[0.9369077]
 [1.1787937]]
[[0.9370423]
 [1.1781496]]
[[0.93712926]
 [1.1774857 ]]
[[0.93726635]
 [1.1768854 ]]
[[0.93756425]
 [1.1763533

[[1.0149522]
 [1.0496671]]
[[1.015041 ]
 [1.0493022]]
[[1.0150739]
 [1.0489401]]
[[1.0150669]
 [1.048524 ]]
[[1.0151236]
 [1.0481467]]
[[1.0152569]
 [1.0478003]]
[[1.0153981]
 [1.047564 ]]
[[1.0156575]
 [1.0475892]]
[[1.0158405]
 [1.0474921]]
[[1.016043 ]
 [1.0473233]]
[[1.0162023]
 [1.0470803]]
[[1.0163674]
 [1.0468936]]
[[1.0165843]
 [1.0466936]]
[[1.0168145]
 [1.0467079]]
[[1.0170876]
 [1.046671 ]]
[[1.0173206]
 [1.0467377]]
[[1.0175048]
 [1.0467275]]
[[1.0176233]
 [1.0466352]]
[[1.0176828]
 [1.0465184]]
[[1.0176994]
 [1.0463233]]
[[1.0177778]
 [1.046145 ]]
[[1.0178424]
 [1.0459278]]
[[1.0179219]
 [1.0458078]]
[[1.0180103]
 [1.0459338]]
[[1.0180389]
 [1.0459276]]
[[1.0181026]
 [1.0458406]]
[[1.018137 ]
 [1.0456711]]
[[1.0181895]
 [1.0455507]]
[[1.0181774]
 [1.0453408]]
[[1.0182016]
 [1.0453461]]
[[1.0182897]
 [1.0453012]]
[[1.0183561]
 [1.0453606]]
[[1.01839  ]
 [1.0453439]]
[[1.018373 ]
 [1.0452456]]
[[1.0183101]
 [1.0451237]]
[[1.0182163]
 [1.0449239]]
[[1.0182815]
 [1.0448762]]
[

 [1.0432329]]
[[1.0193869]
 [1.0434057]]
[[1.0194817]
 [1.0434828]]
[[1.0195408]
 [1.0434645]]
[[1.0196187]
 [1.0434791]]
[[1.019621 ]
 [1.0433946]]
[[1.0196631]
 [1.0435052]]
[[1.0197766]
 [1.0435569]]
[[1.0198641]
 [1.0436995]]
[[1.0199134]
 [1.0437604]]
[[1.0199035]
 [1.0437353]]
[[1.0198404]
 [1.0436803]]
[[1.0197412]
 [1.0435443]]
[[1.0197246]
 [1.0434192]]
[[1.0197029]
 [1.0432523]]
[[1.0197079]
 [1.0431747]]
[[1.0197315]
 [1.0433296]]
[[1.0196944]
 [1.043354 ]]
[[1.0196111]
 [1.0432558]]
[[1.0195097]
 [1.0430799]]
[[1.0194432]
 [1.0429523]]
[[1.019315]
 [1.04274 ]]
[[1.0192399]
 [1.0427356]]
[[1.0192484]
 [1.0426838]]
[[1.0192412]
 [1.0427332]]
[[1.0192051]
 [1.0427103]]
[[1.019118 ]
 [1.0426097]]
[[1.0189849]
 [1.0424868]]
[[1.0188543]
 [1.0424222]]
[[1.0189083]
 [1.042491 ]]
[[1.0189501]
 [1.0424986]]
[[1.0190756]
 [1.0426885]]
[[1.019208 ]
 [1.0430832]]
[[1.0192684]
 [1.0433236]]
[[1.0193666]
 [1.0434619]]
[[1.0194285]
 [1.043499 ]]
[[1.0195092]
 [1.0435632]]
[[1.0195132]
 [1

In [30]:
# 计算5层神经网络带L2正则化的损失函数

def get_weight(shape,lambda0):
    var = tf.Variable(tf.random_normal(shape),dtype=tf.float32)
    tf.add_to_collection(
            'losses',tf.contrib.layers.l2_regularizer(lambda0)(var))
    return var


In [31]:
x = tf.placeholder(tf.float32,shape=(None,2),name='x_input')
y_ = tf.placeholder(tf.float32,shape=(None,1),name='y_input')
batch_size = 8

layer_dimension = [2,10,10,10,1]
n_layers = len(layer_dimension)

cur_layer = x
in_dimension = layer_dimension[0]


In [33]:
for i in range(1,n_layers):
    out_dimension = layer_dimension[i]
    
    weight = get_weight([in_dimension,out_dimension],0.001)
    bias = tf.Variable(tf.constant(0.1,shape=[out_dimension]))
    
    cur_layer = tf.nn.relu(tf.matmul(cur_layer,weight)+bias)
    
    in_dimension = layer_dimension[i]

In [35]:
mse_loss = tf.reduce_mean(tf.square(y_-cur_layer))

tf.add_to_collection('losses',mse_loss)

loss = tf.add_n(tf.get_collection('losses'))